### ISSUE TITLE
remove NAN triples

### ISSUE THREAD

**Issue by wdduncan** [Knowledge-Graph-Hub/kg-covid-19#127]
remove triples that have "nan" as the object. E.g.:
```
<http://ensembl.org/id/ENSP00000000233> <https://www.example.org/UNKNOWN/taxon> "nan"^^<http://www.w3.org/2001/XMLSchema#double> .
```

**Comment by deepakunni3** [comment]
This should now be fixed.

@justaddcoffee Feel free to close this ticket if we don't see this bug anymore

**Comment by justaddcoffee** [comment]
The most recent update seems to get rid of many of these "nan" objects, but I'm still seeing more than a few of these, for example:

```
wget http://kg-hub.berkeleybop.io/kg-covid-19.nt.gz
gzcat kg-covid-19.nt.gz | grep -w '\"nan\"' | more
<http://ensembl.org/id/ENSP00000378332> <https://www.example.org/UNKNOWN/ncbi_taxid> "nan" .
<http://ensembl.org/id/ENSP00000350052> <https://www.example.org/UNKNOWN/ncbi_taxid> "nan" .
<http://ensembl.org/id/ENSP00000343656> <https://www.example.org/UNKNOWN/ncbi_taxid> "nan" .
<http://ensembl.org/id/ENSP00000350199> <https://www.example.org/UNKNOWN/ncbi_taxid> "nan" .
<http://ensembl.org/id/ENSP00000265967> <https://www.example.org/UNKNOWN/ncbi_taxid> "nan" .
<http://ensembl.org/id/ENSP00000367629> <https://www.example.org/UNKNOWN/ncbi_taxid> "nan" .
```

**Comment by deepakunni3** [comment]
Waiting on the Jenkins build 25 to see if this issue has been fixed

**Comment by justaddcoffee** [comment]
These 'nan's are gone now:

```
~/Desktop  $ gzcat kg-covid-19.nt.gz.2 | grep -wi 'nan'
<https://www.example.org/UNKNOWN/TTD_D0L9SN> <http://www.w3.org/2000/01/rdf-schema#label> "NAN-190" .
~/Desktop  $
```

Thanks @deepakunni3 !

**Comment by deepakunni3** [comment]
Finally! That was one pesky bug! 😄
